In [1]:
# Dependencies
from bs4 import BeautifulSoup
import requests
import pymongo
import pandas as pd

In [2]:
# redoing above

# URLs of pages to be scraped
urlList = ["https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/1901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/2901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/3901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/4901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/5901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/6901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/7901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/8901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9001",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9101",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9201",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9301",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9401",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9501",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9601",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9701",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9801",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/9901",
            "https://www.the-numbers.com/box-office-records/worldwide/all-movies/cumulative/all-time/10001"]

# Creating lists to store row results
listAll = pd.DataFrame()

# Retrieve page with the requests module
for url in urlList:
    response = requests.get(url)

    # Create BeautifulSoup object; parse with 'lxml'
    soup = BeautifulSoup(response.text, 'lxml')

    # Grab table #1
    table = soup.find_all('table')[0]
    table_rows = table.find_all('tr')

    list1 = []
    for tr in table_rows:
        td = tr.find_all('td')
        row = [tr.text for tr in td]
        list1.append(row)

    #Grab table #2
    table = soup.find_all('table')[1]
    table_rows = table.find_all('tr')

    list2 = []
    for tr in table_rows:
        td = tr.find_all('td')
        row = [tr.text for tr in td]
        list2.append(row)

    df1 = pd.DataFrame(list1, columns=["Rank", "Release Year", "Movie", "Worldwide Box Office", "Domestic Box Office", "International Box Office"])
    df2 = pd.DataFrame(list2, columns=["Rank", "Release Year", "Movie", "Worldwide Box Office", "Domestic Box Office", "International Box Office"])

    onePageList = pd.concat([df1,df2])
    listAll = pd.concat([listAll,onePageList])

#show listAll df
listAll.head()

,Rank,Release Year,Movie,Worldwide Box Office,Domestic Box Office,International Box Office
0,None,None,None,None,None,None
1,1,2009,Avatar,"$2,776,345,279","$760,507,625","$2,015,837,654"
2,2,1997,Titanic,"$2,208,208,395","$659,363,944","$1,548,844,451"
3,3,2015,Star Wars Ep. VII: The Force Awakens,"$2,053,311,220","$936,662,225","$1,116,648,995"
4,4,2018,Avengers: Infinity War,"$2,048,134,200","$678,815,482","$1,369,318,718"

In [3]:
# Drop empty rows
listAll.dropna(axis=0, how='any', inplace=True)
listAll.head()

,Rank,Release Year,Movie,Worldwide Box Office,Domestic Box Office,International Box Office
1,1,2009,Avatar,"$2,776,345,279","$760,507,625","$2,015,837,654"
2,2,1997,Titanic,"$2,208,208,395","$659,363,944","$1,548,844,451"
3,3,2015,Star Wars Ep. VII: The Force Awakens,"$2,053,311,220","$936,662,225","$1,116,648,995"
4,4,2018,Avengers: Infinity War,"$2,048,134,200","$678,815,482","$1,369,318,718"
5,5,2019,Avengers: Endgame,"$1,785,794,638","$473,894,638","$1,311,900,000"

In [4]:
# Export to csv
listAll.to_csv('movie_list_all.csv',encoding='utf-8')